//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5CentrexDataProcessor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record10
    {
        public int Id { get; set; }
        public string Record_Type { get; set; }
        public string Billing_Telephone_Number { get; set; }
        public string Number_of_Calls { get; set; }
        public string Number_of_Seconds { get; set; }
        public decimal Amount { get; set; }
        public string Invoice_Number { get; set; }
        public string Telephone_Number { get; set; }
        public Nullable<decimal> Rerated_Amount { get; set; }
        public Nullable<decimal> Approved_Rate { get; set; }
    }
}
