//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5CentrexDataProcessor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record09
    {
        public int Id { get; set; }
        public string Record_Type { get; set; }
        public string Billing_Telephone_Number { get; set; }
        public string Call_Date { get; set; }
        public string Call_Time { get; set; }
        public string Call_Duration_Seconds { get; set; }
        public Nullable<decimal> Call_Cost { get; set; }
        public string From_Number { get; set; }
        public string From_City { get; set; }
        public string To_Number { get; set; }
        public string To_City { get; set; }
        public string Call_Type { get; set; }
        public string Usage_Type { get; set; }
        public string Auth_Code { get; set; }
        public string Call_Count { get; set; }
        public string Carrier { get; set; }
        public string Telephone_Number { get; set; }
        public string Provider_Name { get; set; }
        public string Rate_Period { get; set; }
        public string From_State { get; set; }
        public string To_State { get; set; }
        public string Invoice_Number { get; set; }
        public string Call_Duration_Minutes { get; set; }
        public Nullable<decimal> Rerated_Call_Cost { get; set; }
        public string Call_Usage_Type { get; set; }
        public string Source { get; set; }
        public Nullable<decimal> Approved_Rate { get; set; }
    }
}
